image: node:latest

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - node_modules/

install:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/